export const SET_ERROR = 'SET_ERROR';

export const LOAD_MESSAGES_SUCCESS  = 'LOAD_MESSAGES_SUCCESS';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_SUCCESS   = 'EDIT_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';

export const LOGIN_USER_SUCCESS    = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOAD_USER_SUCCESS     = 'LOAD_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS   = 'LOGOUT_USER_SUCCESS';

export const UPDATE_CREATE_MESSAGE_FORM = 'UPDATE_CREATE_MESSAGE_FORM';
export const CLEAR_CREATE_MESSAGE_FORM = 'CLEAR_CREATE_MESSAGE_FORM';
