version: "2"

services:
    mems:
        build: "."
        image: "toksaitov/mems"
        ports:
            - "8890:8890"
        env_file: ".env"
        depends_on:
            - "mems-db"

    mems-db:
        image: "mysql:8"
        command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASS}"
