version: "2"

services:
    mems:
        build: "."
        image: "toksaitov/mems"
        ports:
            - "80:8080"
        env_file: ".env.testing"
        depends_on:
            - "mems-db-test"
            - "mems-session-db-test"

    mems-db-test:
        image: "mysql:5.7.29"
        command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASS}"

    mems-session-db-test:
        image: "redis:5.0.8"

